### ISSUE TITLE
sharing firmware

### ISSUE THREAD

**Issue by inonprince** [sgnh/my-passport-wireless-pro-custom-fw#2]
@sgnh any chance you can share the compiled firmware? thanks!

**Comment by sgnh** [comment]
I can do that but the compiled firmware I have is without the configuration file changes. I've only done those locally after installing the firmware. What features are you looking for specifically?

**Comment by inonprince** [comment]
mainly tmux

**Comment by sgnh** [comment]
You can find the compiled firmware here: https://github.com/sgnh/my-passport-wireless-pro-custom-fw/releases

Changes from official firmware:
- Python setup tools
- Python xml support
- Https support for commandline tools (wget etc.)
- Transmission client for torrents (Unconfigured)
- ZSH
- Tmux
- Vim
- Mac Time capsule support (Unconfigured)

Let me know if you have problems or suggestions. I've not had any problems with it so far, but use it at your own risk 😄

**Comment by inonprince** [comment]
much appreciated.

**Comment by scriptgiddy** [comment]
I know this is closed - but any chance you can share your .config file? I'm new to build root and a little lost with how to get it configured appropriately for this hardware.

**Comment by k3wlar** [comment]
sgnh : Thx :) my passport wireles Pro (Model E6B)
Https support for commandline tools -- Work
Transmission client for torrents (Unconfigured) -- Work
ZSH -- Work
Tmux -- Work
Vim -- Work
Mac Time capsule support (Unconfigured) -- I haven't tried yet but it's just a question of time :)

**Comment by GLLM** [comment]
Hello all, @sgnh

Yeah, I know, commenting on an old/closed issue ...
Just wondering : have you tried to modify/improve the SD copy function so that one does not end up with this horribly long & technical path that is set by WD by default ?
I've tried to look at SDCard_StorageTransfer.sh and al ... but I'm not sure what needs to be changed
So, in case any of you did try ...

Thanks
GLLM
Thanks
